version: 0.2

phases:
  install:
    commands:
      - echo install all dependencies
      - npm install
  pre_build:
    commands:
      - echo No pre-build step
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/**/*